version: '3.4'
services:

  onedrive:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ONEDRIVE_UID=${PUID}
      - ONEDRIVE_GID=${PGID}
      #- ONEDRIVE_ARGS=--monitor --confdir /onedrive/conf --syncdir /onedrive/data
      #- ONEDRIVE_ARGS=--monitor --confdir /onedrive/conf --syncdir /onedrive/data --single-directory Sync
    ports:
      - 8080:8080
    volumes:
      - ./onedrive_conf:/onedrive/conf
      - ./OneDrive:/onedrive/data

# PUID=`id -u` PGID=`id -g` docker-compose up
